version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      # the basic time unit in milliseconds used by ZooKeeper.
      # It is used to do heartbeats and the minimum session timeout will be twice the tickTime
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    depends_on:
      - "zookeeper"
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # https://www.confluent.io/blog/kafka-listeners-explained/
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://localhost:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    depends_on:
      - "zookeeper"
      - "kafka-broker-1"
    ports:
      - "8082:8082"
    container_name: "krp"
    environment:
      KAFKA_REST_HOST_NAME: "kafka-rest-proxy"
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-broker-1:29092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
